repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.13.2"
    hooks:
      - id: ruff-format
      - id: ruff-check
        args: [ "--fix", "--show-fixes", "--unsafe-fixes"]
  - repo: https://github.com/kynan/nbstripout
    rev: "0.8.1"
    hooks:
      - id: nbstripout